<?php
/**
 * Base page template
 *
 * @package    Configure 8 Admin
 * @subpackage Templates
 * @since      1.0.0
 */

?>
<!DOCTYPE html>
<html dir="auto" class="no-js" lang="<?php echo $L->currentLanguageShortVersion(); ?>" xmlns:og="http://opengraphprotocol.org/schema/" data-admin-page>
<head data-admin-head>
	<title><?php echo $layout['title']; ?></title>

	<meta charset="<?php echo CHARSET; ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
	<meta name="robots" content="noindex,nofollow">

	<?php // Preconnect and preload files. ?>
	<link rel="preconnect" href="//fonts.adobe.com" />
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

	<?php

	// Change `<html>` 'no-js' class to 'js' if JavaScript is enabled.
	echo "<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>\n"; ?>

	<link rel="shortcut icon" type="image/x-icon" href="<?php echo HTML_PATH_CORE_IMG . 'favicon.png?version=' . BLUDIT_VERSION; ?>">

	<?php
		echo Theme :: cssLineAwesome();
		echo Theme :: css(
			[
				'jquery.datetimepicker.min.css',
				'select2.min.css',
				'select2-bootstrap4.min.css'
			],
			DOMAIN_CORE_CSS
		);
		echo Theme :: css(
			[
				'assets/css/bootstrap.min.css',
				'assets/css/style.min.css'
			],
			DOMAIN_ADMIN_THEME
		);

		echo Theme :: jquery();
		echo Theme :: jsBootstrap();
		echo Theme :: jsSortable();
		echo Theme :: js(
			[
				'jquery.datetimepicker.full.min.js',
				'select2.full.min.js',
				'functions.js'
			],
			DOMAIN_CORE_JS, null
		);

		Theme :: plugins( 'adminHead' );

		?>
</head>
<body class="bl-admin <?php echo 'admin-page-' . strtok( $url->slug(), '/' ); echo ( str_contains( $url->slug(), '/' ) ? ' admin-' . str_replace( '/', '-', $url->slug() ) : '' ); ?>">

<?php Theme :: plugins( 'adminBodyBegin' ); ?>

<?php
// JavaScript generated by PHP.
	echo '<script charset="utf-8">' . PHP_EOL;
	include( PATH_CORE_JS.'variables.php' );
	echo '</script>' . PHP_EOL;

	echo '<script charset="utf-8">' . PHP_EOL;
	include( PATH_CORE_JS.'bludit-ajax.php' );
	echo '</script>' . PHP_EOL;
?>

<?php

// JavaScript alerts.
echo '<div id="jsshadow"></div>';
include( 'views/alert.php' ); ?>

<?php // include( 'views/menu-mobile.php' ); ?>

<div class="admin-wrapper">

	<div id="admin-menu" class="admin-menu">
		<?php include( 'views/menu.php' ); ?>
	</div>

	<div id="admin-content" class="admin-content">
	<?php
		if ( Sanitize :: pathFile( PATH_ADMIN_VIEWS, $layout['view'] . '.php' ) ) {
			include( PATH_ADMIN_VIEWS.$layout['view'] . '.php' );
		} elseif ( $layout['plugin'] && method_exists( $layout['plugin'], 'adminView' ) ) {
			echo $layout['plugin']->adminView();
		} else {
			echo '<h1 class="text-center">' . $L->g( 'Page not found' ) . '</h1>';
			echo '<h2 class="text-center">' . $L->g( 'Choose a page from the menu.' ) . '</h2>';
		}
	?>
	</div>
</div>

<?php Theme :: plugins( 'adminBodyEnd' ); ?>

</body>
</html>
